import { prisma } from "../lib/prisma";

async function main() {
  console.log("Seeding database with demo users, children, and screenings...");

  // If demo parent and 3 children already exist, skip wipe
  const existingParent = await prisma.user.findUnique({ where: { email: "parent@earlysteps.org" } });
  if (existingParent) {
    const children = await prisma.child.findMany({ where: { userId: existingParent.id } });
    if (children.length >= 3) {
      console.log("✔ EarlySteps database ready with demo parent and children!");
      return;
    }
  }

  // Clean existing demo data
  await prisma.auditLog.deleteMany();
  await prisma.result.deleteMany();
  await prisma.answer.deleteMany();
  await prisma.screening.deleteMany();
  await prisma.child.deleteMany();
  await prisma.consent.deleteMany();
  await prisma.user.deleteMany();

  // 1. Create Demo Parent
  const parent = await prisma.user.create({
    data: {
      email: "parent@earlysteps.org",
      name: "Priya Sharma",
      passwordHash: "Parent@123",
      role: "PARENT",
      consents: {
        create: {
          version: "1.0.0-dpdp2023",
          agreedToDPDP: true,
          termsAccepted: true,
          ipAddress: "127.0.0.1",
          userAgent: "EarlySteps Seeder / Chrome 124",
        },
      },
    },
  });

  // 2. Create Clinician
  await prisma.user.create({
    data: {
      email: "doctor@earlysteps.org",
      name: "Dr. Ananya Roy, MD",
      passwordHash: "Doctor@123",
      role: "CLINICIAN",
    },
  });

  // 3. Create Admin
  await prisma.user.create({
    data: {
      email: "admin@earlysteps.org",
      name: "System Admin",
      passwordHash: "Admin@123",
      role: "ADMIN",
    },
  });

  const now = new Date();
  const subMonths = (date: Date, months: number) => {
    const d = new Date(date);
    d.setMonth(d.getMonth() - months);
    return d.toISOString();
  };

  // Child 1: 14 months old
  const child14m = await prisma.child.create({
    data: {
      userId: parent.id,
      name: "Aarav",
      dateOfBirth: subMonths(now, 14),
      gender: "male",
      isPremature: false,
      gestationalWeeks: null,
    },
  });

  // Child 2: 24 months old (with past screening)
  const child24m = await prisma.child.create({
    data: {
      userId: parent.id,
      name: "Meera",
      dateOfBirth: subMonths(now, 24),
      gender: "female",
      isPremature: false,
      gestationalWeeks: null,
    },
  });

  // Child 3: 40 months old
  const child40m = await prisma.child.create({
    data: {
      userId: parent.id,
      name: "Kabir",
      dateOfBirth: subMonths(now, 40),
      gender: "male",
      isPremature: true,
      gestationalWeeks: 34,
    },
  });

  // Add completed screening for Child 2 (Meera, 24m) -> Medium Risk
  const screening24m = await prisma.screening.create({
    data: {
      childId: child24m.id,
      userId: parent.id,
      questionnaireId: "m-chat-r-16-30",
      status: "COMPLETED",
      totalScore: 4,
      riskLevel: "MEDIUM",
      clinicianNotes: "Parent reports mild joint attention delay and sound reactivity. Follow-up consultation scheduled.",
      completedAt: new Date().toISOString(),
    },
  });

  // Seed sample answers (4 risk indicators: Q2=YES, Q5=YES, Q6=NO, Q12=YES)
  for (let q = 1; q <= 20; q++) {
    let response = "YES";
    let score = 0;
    if (q === 2 || q === 5 || q === 12) {
      response = "YES";
      score = 1;
    } else if (q === 6) {
      response = "NO";
      score = 1;
    } else {
      response = "YES";
      score = 0;
    }

    await prisma.answer.create({
      data: {
        screeningId: screening24m.id,
        questionId: q,
        response,
        scoreValue: score,
      },
    });
  }

  // Seed Result
  await prisma.result.create({
    data: {
      screeningId: screening24m.id,
      riskLevel: "MEDIUM",
      score: 4,
      summary: "Your responses indicate some developmental milestones may benefit from clinical follow-up.",
      recommendationsJson: JSON.stringify([
        "Schedule an appointment with your pediatrician or developmental specialist for a structured follow-up interview.",
        "Download and take the PDF report generated by this screening to your doctor's visit.",
        "Observe your child's responses to name calls and pointing in various calm home settings.",
      ]),
    },
  });

  // Audit Log
  await prisma.auditLog.create({
    data: {
      userId: parent.id,
      action: "DEMO_SEED_COMPLETED",
      resourceType: "System",
      resourceId: parent.id,
      details: "Seed script populated demo parent and 3 children (14m, 24m, 40m)",
      ipAddress: "127.0.0.1",
    },
  });

  console.log("✔ Database successfully seeded!");
  console.log(`- Demo Parent: Priya Sharma (${parent.email})`);
  console.log(`  - Child 1: Aarav (14 months, ID: ${child14m.id})`);
  console.log(`  - Child 2: Meera (24 months, completed screening: Medium risk, ID: ${child24m.id})`);
  console.log(`  - Child 3: Kabir (40 months, premature 34w, ID: ${child40m.id})`);
  console.log(`- Demo Clinician: Dr. Ananya Roy (doctor@earlysteps.org)`);
  console.log(`- System Admin: System Admin (admin@earlysteps.org)`);
}

main()
  .catch((e) => {
    console.error("Error seeding database:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
